Create a pandas series tjat contains the following data: 4, 8, 15, 16,
23, and 42. Then print the series.

In \[ \]:

    import pandas as pd
    df=[4,8,15,16,23,42]
    df1=pd.Series(df)
    print(df1)

    0     4
    1     8
    2    15
    3    16
    4    23
    5    42
    dtype: int64

Create a variable of list type containing 10 elements in it, and apply
pandas. Series function on the variable print it.

In \[ \]:

    import pandas as pd


    my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


    my_series = pd.Series(my_list)
    print(my_series)

    0     10
    1     20
    2     30
    3     40
    4     50
    5     60
    6     70
    7     80
    8     90
    9    100
    dtype: int64

Create a Pandas DataFrame that contains the following data: Name: Alice,
Bob, Claire Age: 25, 30, 27 Gender: Female, Male, Female then, print the
dataframe

In \[ \]:

    import pandas as pd


    data = {
        "Name": ['Alice', 'Bob', 'Claire'],
        "Age": [25, 30, 27],
        "Gender": ['Female', 'Male', 'Female']
    }

    df = pd.DataFrame(data)


    print(df)

         Name  Age  Gender
    0   Alice   25  Female
    1     Bob   30    Male
    2  Claire   27  Female

What is 'Dataframe' in pandas and how is it different from pandas.series
? Explain with example.

In pandas, a DataFrame is a two-dimensional tabular data structure,
similar to a spreadsheet or SQL table. It consists of rows and columns,
where each column can hold data of a different data type (e.g., integer,
float, string). A DataFrame is the primary data structure used for data
manipulation and analysis in pandas.

On the other hand, a pandas Series is a one-dimensional labeled array
that can hold data of a single data type. It can be thought of as a
single column from a DataFrame. A Series has both data and an associated
index that labels each element of the data.

Let's illustrate the difference between DataFrame and Series with an
example: import pandas as pd

# Example 1: Creating a DataFrame<a href="#Example-1:-Creating-a-DataFrame" class="anchor-link">¶</a>

data = { 'Name': \['Alice', 'Bob', 'Charlie'\], 'Age': \[25, 30, 35\],
'City': \['New York', 'London', 'Tokyo'\] }

df = pd.DataFrame(data) print("DataFrame:") print(df)

In this example, we create a DataFrame with three columns ('Name',
'Age', and 'City') and three rows of data. Each column can be considered
a Series, with its own data and index. For instance, if we access the
'Name' column, we will get a Series:

name_series = df\['Name'\] print("Series - Name:") print(name_series)

The output shows a Series with index (0, 1, 2) and data ('Alice', 'Bob',
'Charlie').

So, in summary:

# A DataFrame is a two-dimensional data structure with rows and columns, and each column is a Series.<a
href="#A-DataFrame-is-a-two-dimensional-data-structure-with-rows-and-columns,-and-each-column-is-a-Series."
class="anchor-link">¶</a>

# A Series is a one-dimensional data structure with an index and data of the same data type.<a
href="#A-Series-is-a-one-dimensional-data-structure-with-an-index-and-data-of-the-same-data-type."
class="anchor-link">¶</a>

Both DataFrame and Series are powerful tools for data manipulation and
analysis, and pandas provides a wide range of methods to work with them.

What are some common functions you can use to manipultate data in a
pandas dataframe ? Can you give an example of when you might use one of
these functions?

Pandas provides a rich set of functions for data manipulation in a
DataFrame. Some common functions include:

1.Filtering: Use functions like loc and iloc to select specific rows or
columns based on conditions.

import pandas as pd

data = { 'Name': \['Alice', 'Bob', 'Charlie'\], 'Age': \[25, 30, 35\],
'City': \['New York', 'London', 'Tokyo'\] }

df = pd.DataFrame(data)

# Filtering rows based on a condition<a href="#Filtering-rows-based-on-a-condition" class="anchor-link">¶</a>

filtered_df = df.loc\[df\['Age'\] \> 30\] print(filtered_df)

Aggregation: Use functions like groupby to group data based on certain
columns and apply aggregate functions like sum, mean, count, etc.

# Aggregating data based on a column<a href="#Aggregating-data-based-on-a-column" class="anchor-link">¶</a>

grouped_df = df.groupby('City')\['Age'\].mean() print(grouped_df)

Sorting: Use sort_values to sort the DataFrame based on one or more
columns.

# Sorting data<a href="#Sorting-data" class="anchor-link">¶</a>

sorted_df = df.sort_values(by='Age', ascending=False) print(sorted_df)

Adding or Removing Columns: Use indexing or assign method to add new
columns to the DataFrame, or use drop method to remove columns.

# Adding a new column<a href="#Adding-a-new-column" class="anchor-link">¶</a>

df\['Gender'\] = \['Female', 'Male', 'Male'\]

# Removing a column<a href="#Removing-a-column" class="anchor-link">¶</a>

df = df.drop('Age', axis=1) print(df)

Missing Data Handling: Use functions like dropna to remove rows with
missing data, or fillna to fill missing data with specified values.

# Handling missing data<a href="#Handling-missing-data" class="anchor-link">¶</a>

df_with_nan = pd.DataFrame({'A': \[1, 2, None, 4, 5\]}) cleaned_df =
df_with_nan.dropna() print(cleaned_df)

filled_df = df_with_nan.fillna(0) print(filled_df)

Which of the following is mutable in nature Series, Dataframe, Panel?

In the context of pandas, which is a popular data manipulation library
in Python, the following is true regarding mutability:

Series: Mutable A pandas Series is mutable, meaning you can change the
values of individual elements in the Series after it has been created.

DataFrame: Mutable A pandas DataFrame is also mutable, allowing you to
modify its data, add or remove columns, and make other changes to the
structure and content.

Panel: Mutable Panels were a data structure in pandas for 3-dimensional
data. However, starting from pandas version 0.25.0, the Panel data
structure was deprecated and removed from pandas because it was not
widely used and could be adequately represented using other data
structures like DataFrames and MultiIndex DataFrames.

Since panels are no longer part of pandas, it's essential to focus on
Series and DataFrame, both of which are mutable in nature.

Create a Dataframe using multiple Series. Explain with an example.

Creating a DataFrame using multiple Series in pandas is a common
operation when working with tabular data. A DataFrame is a
two-dimensional data structure that can hold data in rows and columns,
similar to a table or spreadsheet. To create a DataFrame from multiple
Series, you can use the pd.DataFrame() constructor provided by pandas.

Here's an example of how to create a DataFrame using multiple Series:

import pandas as pd

# Sample data in the form of Series<a href="#Sample-data-in-the-form-of-Series" class="anchor-link">¶</a>

names = pd.Series(\['Alice', 'Bob', 'Charlie', 'David'\]) ages =
pd.Series(\[25, 30, 28, 22\]) scores = pd.Series(\[85, 90, 78, 92\])

# Create a DataFrame from the Series<a href="#Create-a-DataFrame-from-the-Series" class="anchor-link">¶</a>

data = { 'Name': names, 'Age': ages, 'Score': scores }

df = pd.DataFrame(data)

print(df) Output:

      Name  Age  Score

0 Alice 25 85 1 Bob 30 90 2 Charlie 28 78 3 David 22 92 In this example,
we first create three different Series: names, ages, and scores, each
containing data for the 'Name', 'Age', and 'Score' columns,
respectively.

Then, we create a dictionary data where the keys are column names
('Name', 'Age', and 'Score') and the values are the corresponding
Series.

Finally, we pass the data dictionary to the pd.DataFrame() constructor,
which creates a DataFrame named df with three columns ('Name', 'Age',
and 'Score') and four rows of data.

Each Series will become a column in the DataFrame, and their indices are
automatically aligned to form the rows of the DataFrame. The resulting
DataFrame holds the data in a structured tabular format, making it easy
to perform various data manipulations and analysis.